CONFIGFILES := config.txt template-slot6 template-slot7
CONFIGDIR := /opt/retropie/configs/apple2
INSTALLDIR := /opt/retropie/emulators/gsplus

install:
	install ../../build/bin/GSplus ${INSTALLDIR}
	install gsplus.sh ${INSTALLDIR}
	install ${CONFIGFILES} ${CONFIGDIR}

