FILES := config.txt template-slot6 template-slot7
CONFIG_PREFIX := /opt/retropie/configs/apple2
INSTALL_PREFIX := /opt/retropie/emulators/gsplus

install:
	install gsplus.sh ${INSTALL_PREFIX}
	install ${FILES} ${CONFIG_PREFIX}

